### ISSUE TITLE
Limit the quantity of plants produced in the Punnett square

### ISSUE THREAD

**Issue by smockle** [SainTfactor/Mendulum#1]
Currently, an unlimited number of each offspring plant can be removed from the Punnett square. Limit this to one plant from each of the four spots.

**Comment by Alressun** [comment]
Why?

**Comment by smockle** [comment]
It's not essential, I guess. It's just more intuitive--you are picking a plant. And it maintains consistency with the way plants work in the top and left (parent) spots, and in the basket.

**Comment by smockle** [comment]
> <cite>@Alressun</cite> I think I'm going to leave it being possible to keep grabbing stuff out of the square because I think it would take too long to change

Closing as WONTFIX.
