### ISSUE TITLE
Don't animate the note plants on click

### ISSUE THREAD

**Issue by smockle** [SainTfactor/Mendulum#2]
Currently, when you click a plant in the note at the top-left of the screen, it begins to shake. Remove the shake animation from the note plants.

**Comment by Alressun** [comment]
Feature

**Comment by smockle** [comment]
The jittering implies interactivity. It makes sense for the plants in the plot and the basket. But the note plants are not interactive.

**Comment by Alressun** [comment]
Oh, fine

**Comment by smockle** [comment]
Closed by @c7319cc95fec9b7c3057784ac20812677d45356e.
