### ISSUE TITLE
Indicate when the player has won

### ISSUE THREAD

**Issue by smockle** [SainTfactor/Mendulum#3]
Currently, when the plants in your basket match the plants in the note, nothing happens to indicate that you have won, and the game does not end (each plant remains interactive).

**Comment by Alressun** [comment]
Probably a problem with your build settings

**Comment by smockle** [comment]
How can I build the project so that the "win" scene is properly displayed? I'll need this for our screencast.

**Comment by smockle** [comment]
> <cite>@Alressun</cite> Open main.unity, go to build settings, then press add current. Then repeat for win.unity. The win screen should work now.

This worked for me.
